print ('Hello World ')
print('hii')
print ('Hello World ')
print('hii')
print ('Hello World ')
print('hii')
print ('Hello World ')
print('hii')
print ('Hello World ')
print('hii')
print ('Hello World ')
print('hii')